version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.11.0
  go: circleci/go@1.7.0

executors:
  # Whenever the Go version is updated here, .promu.yml
  # should also be updated.
  golang:
    docker:
      - image: circleci/golang:1.16-node

jobs:
  test:
    executor: golang

    steps:
      - prometheus/setup_environment
      - go/load-cache:
          key: v1-go-mod
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "web/ui/react-app/yarn.lock" }}
            - v1-npm-deps-
      - run:
          command: make
          environment:
            # By default, Go uses GOMAXPROCS but a Circle CI executor has many
            # cores (> 30) while the CPU and RAM resources are throttled. If we
            # don't limit this to the number of allocated cores, the job is
            # likely to get OOMed and killed.
            GOOPTS: "-p 2"
            GOMAXPROCS: "2"
            GO111MODULE: "on"
      - prometheus/store_artifact:
          file: prometheus-webhook-dingtalk
      - go/save-cache:
          key: v1-go-mod
      - save_cache:
          key: v1-npm-deps-{{ checksum "web/ui/react-app/yarn.lock" }}
          paths:
            - web/ui/react-app/node_modules
  build:
    description: >
      Cross-build and store the binaries.
    machine:
      enabled: true

    steps:
      - prometheus/setup_environment
      - run: promu crossbuild -v
      - persist_to_workspace:
          root: .
          paths:
            - .build
      - store_artifacts:
          path: .build
          destination: /build

workflows:
  version: 2
  prometheus-webhook-dingtalk:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          name: build
          filters:
            tags:
              only: /.*/
      - prometheus/publish_master:
          context: timonwong-context
          requires:
            - test
            - build
          filters:
            branches:
              only: master
          image: circleci/golang:1-node
          quay_io_organization: ''
          docker_hub_organization: timonwong
      - prometheus/publish_release:
          context: timonwong-context
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
          image: circleci/golang:1-node
          quay_io_organization: ''
          docker_hub_organization: timonwong
